name: List 8

on:
  push:
    branches:
      - main  # این باعث میشه هر بار که تغییری در branch اصلی push بشه، workflow اجرا بشه
  schedule:
    - cron: '*/8 * * * *'  # این باعث میشه هر فلان دقیقه یک بار اجرا بشه

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping project URL
        run: curl -s https://brindle-pale-mockingbird.glitch.me > /dev/null  # URL پروژه‌ات رو وارد کن
